# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/Arden-Cho"

    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "telegram"
    name       = "Telegram"
    url        = "https://t.me/imarden1"

    [social.params]
        icon = "brand-telegram"

[[social]]
    identifier = "discord"
    name       = "Discord"
    url        = "https://discord.com/users/876382458893963265"

    [social.params]
        icon = "brand-discord"
